###### (2020) Gonzalo G. Peraza Mues

# Numpy Exercises

Vamos a resolver algunos ejercicios sencillos con Numpy.

In [1]:
import numpy as np

# Definimos un vector
x = np.array([1, 2, 3, 4, 5])
# Y una matriz
m = np.array([[1, 2, 3],[4, 5, 6,], [7, 8, 9]])

In [2]:
print(x)

[1 2 3 4 5]


In [3]:
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Una operación común que querrá hacer con
vectores o matrices es sumar cada elemento.
La notación puede dar miedo, pero en realidad es
bastante simple:
$$
\sum_{i,j = 1}^n m_{ij}
$$
El símbolo $\Sigma$ es $\sigma$ mayúscula
y se llama "sigma". Significa que para alguna matriz $m$, donde $i$ representa una fila y $j$ representa una columna, sume todos los elementos. $n$ se refiere al número de elementos de la variable $m$.

Aunque puede implementar esta operación usando un bucle for, NumPy lo hace fácil al proporcionar un método `sum`.

Intente implementarlo ahora `m.sum ()`, debes obetener el valor 45.

In [4]:
result = 0
#get the number of rows
rows = len(m)
 
#get the number of columns
cols = len(m[0])
for i in range(0,rows):
  for j in range(0, cols):
    result = result + m[i, j]
print(result)

45


In [5]:
m.sum()

45

Otra operación común es multiplicar cada
valor en un vector o matriz. Esto parece
esto:
$$
\prod_{i,j=1}^n m_{ij}
$$

El símbolo $\Pi$ es un símbolo $\pi$ mayúscula, pronunciado "pi". Implemente esta ecuación de manera similar usando la función `prod`, debe obtener 362880. 

In [6]:
m.prod()

362880

¡Estupendo! Ahora está listo para implementar algunos
ecuaciones básicas! Empecemos con la
media aritmética:
$$
\bar{x} = \frac{1}{n}\times \sum_{i=1}^n x_i
$$

Esto simplemente significa agregar cada elemento de un
lista y dividiendo el resultado por el número de
elementos en $ x $. Una barra sobre una variable ($ \bar {x} $) se refiere a un tipo de media.

**Hint:** Puedes obtener la cantidad de elementos
en una matriz en NumPy con `x.size` ..

In [ ]:
# You must return this variable correctly
mean = 0

mean = x.sum()/x.size

print(f'Calulaste una media de {mean}, debería ser 3.0')

Calulaste una media de 3.0, debería ser 3.0


¡Buen trabajo! Ahora implementemos algo conocido
como la norma Frobenius:
$$
\Vert m \Vert_F = \left(
    \sum_{i,j=1}^n m_{ij}^2
    \right)^{1/2}
$$

**Hint:** Puede implementar esto de varias formas, usando operadores (`**`), funciones (`np.sqrt`) y métodos (` .sum`).

In [ ]:
# You must return this variable correctly
f_norm = 0

f_norm = np.sqrt((m**2).sum())

print(f'You found f_norm to be {round(f_norm, 4)}, it shoulb be 16.8819')

You found f_norm to be 16.8819, it shoulb be 16.8819


¡Perfecto! Ahora, para su desafío final, implementemos la desviación estándar:
$$
\sqrt{\frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2}
$$

Recuerde que $ \bar {x} $ se refiere a la media aritmética de $ x $.
En lugar de implementarlo desde cero, simplemente puede llamar a `x.mean ()`.


In [ ]:
# You must return this variable correctly
sd = 0

sd = np.sqrt(np.sum((x - x.mean())**2) / (x.size - 1))

print(f'You found sd to be {round(sd, 4)}, it shoulb be 1.5811')

You found sd to be 1.5811, it shoulb be 1.5811


Como un último reto, vamos a calcular una matriz de distancias en numpy.
Implementa una función que tome como entrada una matrix de datos, donde cada fila es una observación y cada columna una variable, y devuelva otra matriz, la matriz de distancias.

La matriz de distancias es muy utilizado en algoritmos de aprendizaje y tiene la siguiente forma:

$$
D = \begin{pmatrix}
d(x_1,x_1) & d(x_1,x_2) & \dots & d(x_1,x_n)\\
d(x_2,x_1) & d(x_2,x_2) & \dots & d(x_2,x_n)\\
\vdots & \vdots & \ddots & \vdots\\
d(x_n,x_1) & d(x_n,x_2) & \dots & d(x_n,x_n)
\end{pmatrix}
$$

Es una matrix NxN, donde N es el número de observaciones en la matriz de datos. Cada entrada de la matriz $d(x_i,x_j)$ es la distancia entre observación $i$ y $j$, y se calcula como

$$
d(x_i,x_j) = \sqrt{\sum_l (x_{il} - x_{jl})^2}
$$

Es decir, resta cada variable, elemento por elemento, de los vectores de observación, eleva las restas al cuadrado y suma todas. Al final saca la raíz. Esta es la distancia euclidiana o norma-2.

Una de las maneras mas eficientes en computo, aunque no en memoria, es hacer un broadcast en 3D, aunque no es la única manera.

In [ ]:
row = m.shape[0]
cols = m.shape[1]
print(f'La matriz tiene {row} filas y {cols} columnas')

La matriz tiene 3 filas y 3 columnas


In [ ]:
enumerate?

In [ ]:
def distance_matrix(X):
    """Returns the distance matrix from a data matrix X. """
    row = m.shape[0]
    cols = m.shape[1] 
    D = np.zeros((row,cols))

    for i, x1 in enumerate(X):
      for j, x2 in enumerate(X):
        D[i,j] = np.sqrt(np.sum((x1 - x2)**2))
    
    return D

D = distance_matrix(m)

In [ ]:
D

array([[ 0.        ,  5.19615242, 10.39230485],
       [ 5.19615242,  0.        ,  5.19615242],
       [10.39230485,  5.19615242,  0.        ]])

In [ ]:
np.sqrt(np.sum((m[:,None,:] - m[None,:,:])**2, axis=-1))

array([[ 0.        ,  5.19615242, 10.39230485],
       [ 5.19615242,  0.        ,  5.19615242],
       [10.39230485,  5.19615242,  0.        ]])

## References
- Adapted from: https://mathtocode.com/ by Vernon Thommeret